### ISSUE TITLE
Simple birth-and-death process probabilities do not sum to 1

### ISSUE THREAD

**Issue by albertopessia** [msuchard/MultiBD#5]
If I understood the model correctly, the following rates in a birth/birth-death process should correspond to a simple (linear) birth-and-death process:

lambda_1 = 0
lambda_2 = b * lambda
mu_2 = b * mu
trans_12 = 0

but when I try to sum all the probabilities from 0 to a large number, I get a value very far from 1:

```r
library(MultiBD)

lambda <- 1.0
mu <- 2.0

brates1 <- function(a, b) { 0 }
brates2 <- function(a, b) { b  * lambda }
drates2 <- function(a, b) { b * mu }
trans21 <- function(a, b) { 0 }

p <- bbd_prob(t=2.0, a0=0, b0=100, brates1, brates2, drates2, trans21, A=0, B=1000)

sprintf("%.20f", sum(p))
```

Note that most of the values are zero, so increasing the upper bound does not improve the accuracy.
I don't understand if I misinterpreted the model or there is a bug in the code.

If it is not a bug, what rates should I define to obtain a simple death-and-birth process?

**Comment by lamho86** [comment]
Sorry for a late reply.  For this example, b0= 100 is quite large, thus introduces numerical errors. If you set b0 = 70, the sum will be 1.

**Comment by slwu89** [comment]
Hi @lamho86, I am also trying to use the MultiBD package, are there any tips/rules to choose these parameters that will avoid numerical errors?

**Comment by lamho86** [comment]
Hi @slwu89 ,
It is more about how far the distribution at time t from the starting point. A safe condition is that the support of the distribution at time t is mostly within (b0 - 50, b0  + 50). For example, 

p <- bbd_prob(t=0.5, a0=0, b0=100, brates1, brates2, drates2, trans21, A=0, B=1000)

works because the above condition is satisfied.
